// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file.proto
#ifndef GRPC_file_2eproto__INCLUDED
#define GRPC_file_2eproto__INCLUDED

#include "file.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace FileService {

class FileTransport final {
 public:
  static constexpr char const* service_full_name() {
    return "FileService.FileTransport";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 客户端流式上传
    std::unique_ptr< ::grpc::ClientWriterInterface< ::FileService::UploadRequest>> UploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::FileService::UploadRequest>>(UploadFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::FileService::UploadRequest>> AsyncUploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::FileService::UploadRequest>>(AsyncUploadFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::FileService::UploadRequest>> PrepareAsyncUploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::FileService::UploadRequest>>(PrepareAsyncUploadFileRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::FileService::DownloadResponse>> DownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::FileService::DownloadResponse>>(DownloadFileRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::FileService::DownloadResponse>> AsyncDownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::FileService::DownloadResponse>>(AsyncDownloadFileRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::FileService::DownloadResponse>> PrepareAsyncDownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::FileService::DownloadResponse>>(PrepareAsyncDownloadFileRaw(context, request, cq));
    }
    // 新增：断点查询接口
    virtual ::grpc::Status QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::FileService::UploadStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FileService::UploadStatus>> AsyncQueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FileService::UploadStatus>>(AsyncQueryUploadStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FileService::UploadStatus>> PrepareAsyncQueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FileService::UploadStatus>>(PrepareAsyncQueryUploadStatusRaw(context, request, cq));
    }
    virtual ::grpc::Status QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::FileService::DownloadStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FileService::DownloadStatus>> AsyncQueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FileService::DownloadStatus>>(AsyncQueryDownloadStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FileService::DownloadStatus>> PrepareAsyncQueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FileService::DownloadStatus>>(PrepareAsyncQueryDownloadStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 客户端流式上传
      virtual void UploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::ClientWriteReactor< ::FileService::UploadRequest>* reactor) = 0;
      virtual void DownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest* request, ::grpc::ClientReadReactor< ::FileService::DownloadResponse>* reactor) = 0;
      // 新增：断点查询接口
      virtual void QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::FileService::UploadRequest>* UploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::FileService::UploadRequest>* AsyncUploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::FileService::UploadRequest>* PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::FileService::DownloadResponse>* DownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::FileService::DownloadResponse>* AsyncDownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::FileService::DownloadResponse>* PrepareAsyncDownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FileService::UploadStatus>* AsyncQueryUploadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FileService::UploadStatus>* PrepareAsyncQueryUploadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FileService::DownloadStatus>* AsyncQueryDownloadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FileService::DownloadStatus>* PrepareAsyncQueryDownloadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::FileService::UploadRequest>> UploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::FileService::UploadRequest>>(UploadFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::FileService::UploadRequest>> AsyncUploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::FileService::UploadRequest>>(AsyncUploadFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::FileService::UploadRequest>> PrepareAsyncUploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::FileService::UploadRequest>>(PrepareAsyncUploadFileRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::FileService::DownloadResponse>> DownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::FileService::DownloadResponse>>(DownloadFileRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::FileService::DownloadResponse>> AsyncDownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::FileService::DownloadResponse>>(AsyncDownloadFileRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::FileService::DownloadResponse>> PrepareAsyncDownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::FileService::DownloadResponse>>(PrepareAsyncDownloadFileRaw(context, request, cq));
    }
    ::grpc::Status QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::FileService::UploadStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FileService::UploadStatus>> AsyncQueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FileService::UploadStatus>>(AsyncQueryUploadStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FileService::UploadStatus>> PrepareAsyncQueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FileService::UploadStatus>>(PrepareAsyncQueryUploadStatusRaw(context, request, cq));
    }
    ::grpc::Status QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::FileService::DownloadStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FileService::DownloadStatus>> AsyncQueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FileService::DownloadStatus>>(AsyncQueryDownloadStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FileService::DownloadStatus>> PrepareAsyncQueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FileService::DownloadStatus>>(PrepareAsyncQueryDownloadStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::ClientWriteReactor< ::FileService::UploadRequest>* reactor) override;
      void DownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest* request, ::grpc::ClientReadReactor< ::FileService::DownloadResponse>* reactor) override;
      void QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response, std::function<void(::grpc::Status)>) override;
      void QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response, std::function<void(::grpc::Status)>) override;
      void QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::FileService::UploadRequest>* UploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response) override;
    ::grpc::ClientAsyncWriter< ::FileService::UploadRequest>* AsyncUploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::FileService::UploadRequest>* PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::FileService::DownloadResponse>* DownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request) override;
    ::grpc::ClientAsyncReader< ::FileService::DownloadResponse>* AsyncDownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::FileService::DownloadResponse>* PrepareAsyncDownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FileService::UploadStatus>* AsyncQueryUploadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FileService::UploadStatus>* PrepareAsyncQueryUploadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FileService::DownloadStatus>* AsyncQueryDownloadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FileService::DownloadStatus>* PrepareAsyncQueryDownloadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UploadFile_;
    const ::grpc::internal::RpcMethod rpcmethod_DownloadFile_;
    const ::grpc::internal::RpcMethod rpcmethod_QueryUploadStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_QueryDownloadStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 客户端流式上传
    virtual ::grpc::Status UploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::FileService::UploadRequest>* reader, ::FileService::UploadResponse* response);
    virtual ::grpc::Status DownloadFile(::grpc::ServerContext* context, const ::FileService::DownloadRequest* request, ::grpc::ServerWriter< ::FileService::DownloadResponse>* writer);
    // 新增：断点查询接口
    virtual ::grpc::Status QueryUploadStatus(::grpc::ServerContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response);
    virtual ::grpc::Status QueryDownloadStatus(::grpc::ServerContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UploadFile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::FileService::UploadRequest>* /*reader*/, ::FileService::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::FileService::UploadResponse, ::FileService::UploadRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DownloadFile() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::FileService::DownloadRequest* /*request*/, ::grpc::ServerWriter< ::FileService::DownloadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDownloadFile(::grpc::ServerContext* context, ::FileService::DownloadRequest* request, ::grpc::ServerAsyncWriter< ::FileService::DownloadResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryUploadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_QueryUploadStatus() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_QueryUploadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUploadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryUploadRequest* /*request*/, ::FileService::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryUploadStatus(::grpc::ServerContext* context, ::FileService::QueryUploadRequest* request, ::grpc::ServerAsyncResponseWriter< ::FileService::UploadStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryDownloadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_QueryDownloadStatus() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_QueryDownloadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDownloadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryDownloadRequest* /*request*/, ::FileService::DownloadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryDownloadStatus(::grpc::ServerContext* context, ::FileService::QueryDownloadRequest* request, ::grpc::ServerAsyncResponseWriter< ::FileService::DownloadStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UploadFile<WithAsyncMethod_DownloadFile<WithAsyncMethod_QueryUploadStatus<WithAsyncMethod_QueryDownloadStatus<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UploadFile() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::FileService::UploadRequest, ::FileService::UploadResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::FileService::UploadResponse* response) { return this->UploadFile(context, response); }));
    }
    ~WithCallbackMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::FileService::UploadRequest>* /*reader*/, ::FileService::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::FileService::UploadRequest>* UploadFile(
      ::grpc::CallbackServerContext* /*context*/, ::FileService::UploadResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DownloadFile() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::FileService::DownloadRequest, ::FileService::DownloadResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::FileService::DownloadRequest* request) { return this->DownloadFile(context, request); }));
    }
    ~WithCallbackMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::FileService::DownloadRequest* /*request*/, ::grpc::ServerWriter< ::FileService::DownloadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::FileService::DownloadResponse>* DownloadFile(
      ::grpc::CallbackServerContext* /*context*/, const ::FileService::DownloadRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_QueryUploadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_QueryUploadStatus() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::FileService::QueryUploadRequest, ::FileService::UploadStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response) { return this->QueryUploadStatus(context, request, response); }));}
    void SetMessageAllocatorFor_QueryUploadStatus(
        ::grpc::MessageAllocator< ::FileService::QueryUploadRequest, ::FileService::UploadStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::FileService::QueryUploadRequest, ::FileService::UploadStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_QueryUploadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUploadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryUploadRequest* /*request*/, ::FileService::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryUploadStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::FileService::QueryUploadRequest* /*request*/, ::FileService::UploadStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_QueryDownloadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_QueryDownloadStatus() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::FileService::QueryDownloadRequest, ::FileService::DownloadStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response) { return this->QueryDownloadStatus(context, request, response); }));}
    void SetMessageAllocatorFor_QueryDownloadStatus(
        ::grpc::MessageAllocator< ::FileService::QueryDownloadRequest, ::FileService::DownloadStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::FileService::QueryDownloadRequest, ::FileService::DownloadStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_QueryDownloadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDownloadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryDownloadRequest* /*request*/, ::FileService::DownloadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryDownloadStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::FileService::QueryDownloadRequest* /*request*/, ::FileService::DownloadStatus* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UploadFile<WithCallbackMethod_DownloadFile<WithCallbackMethod_QueryUploadStatus<WithCallbackMethod_QueryDownloadStatus<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UploadFile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::FileService::UploadRequest>* /*reader*/, ::FileService::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DownloadFile() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::FileService::DownloadRequest* /*request*/, ::grpc::ServerWriter< ::FileService::DownloadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_QueryUploadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_QueryUploadStatus() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_QueryUploadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUploadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryUploadRequest* /*request*/, ::FileService::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_QueryDownloadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_QueryDownloadStatus() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_QueryDownloadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDownloadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryDownloadRequest* /*request*/, ::FileService::DownloadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UploadFile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::FileService::UploadRequest>* /*reader*/, ::FileService::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DownloadFile() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::FileService::DownloadRequest* /*request*/, ::grpc::ServerWriter< ::FileService::DownloadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDownloadFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryUploadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_QueryUploadStatus() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_QueryUploadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUploadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryUploadRequest* /*request*/, ::FileService::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryUploadStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryDownloadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_QueryDownloadStatus() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_QueryDownloadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDownloadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryDownloadRequest* /*request*/, ::FileService::DownloadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryDownloadStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UploadFile() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->UploadFile(context, response); }));
    }
    ~WithRawCallbackMethod_UploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::FileService::UploadRequest>* /*reader*/, ::FileService::UploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* UploadFile(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DownloadFile() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->DownloadFile(context, request); }));
    }
    ~WithRawCallbackMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::FileService::DownloadRequest* /*request*/, ::grpc::ServerWriter< ::FileService::DownloadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* DownloadFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_QueryUploadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_QueryUploadStatus() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->QueryUploadStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_QueryUploadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryUploadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryUploadRequest* /*request*/, ::FileService::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryUploadStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_QueryDownloadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_QueryDownloadStatus() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->QueryDownloadStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_QueryDownloadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDownloadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryDownloadRequest* /*request*/, ::FileService::DownloadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryDownloadStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryUploadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_QueryUploadStatus() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::FileService::QueryUploadRequest, ::FileService::UploadStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::FileService::QueryUploadRequest, ::FileService::UploadStatus>* streamer) {
                       return this->StreamedQueryUploadStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_QueryUploadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryUploadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryUploadRequest* /*request*/, ::FileService::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryUploadStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FileService::QueryUploadRequest,::FileService::UploadStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryDownloadStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_QueryDownloadStatus() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::FileService::QueryDownloadRequest, ::FileService::DownloadStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::FileService::QueryDownloadRequest, ::FileService::DownloadStatus>* streamer) {
                       return this->StreamedQueryDownloadStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_QueryDownloadStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryDownloadStatus(::grpc::ServerContext* /*context*/, const ::FileService::QueryDownloadRequest* /*request*/, ::FileService::DownloadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryDownloadStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FileService::QueryDownloadRequest,::FileService::DownloadStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_QueryUploadStatus<WithStreamedUnaryMethod_QueryDownloadStatus<Service > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_DownloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_DownloadFile() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::FileService::DownloadRequest, ::FileService::DownloadResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::FileService::DownloadRequest, ::FileService::DownloadResponse>* streamer) {
                       return this->StreamedDownloadFile(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_DownloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DownloadFile(::grpc::ServerContext* /*context*/, const ::FileService::DownloadRequest* /*request*/, ::grpc::ServerWriter< ::FileService::DownloadResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedDownloadFile(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::FileService::DownloadRequest,::FileService::DownloadResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_DownloadFile<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_DownloadFile<WithStreamedUnaryMethod_QueryUploadStatus<WithStreamedUnaryMethod_QueryDownloadStatus<Service > > > StreamedService;
};

}  // namespace FileService


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_file_2eproto__INCLUDED
