// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file.proto

#include "file.pb.h"
#include "file.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace FileService {

static const char* FileTransport_method_names[] = {
  "/FileService.FileTransport/UploadFile",
  "/FileService.FileTransport/DownloadFile",
  "/FileService.FileTransport/QueryUploadStatus",
  "/FileService.FileTransport/QueryDownloadStatus",
};

std::unique_ptr< FileTransport::Stub> FileTransport::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileTransport::Stub> stub(new FileTransport::Stub(channel, options));
  return stub;
}

FileTransport::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_UploadFile_(FileTransport_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_DownloadFile_(FileTransport_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_QueryUploadStatus_(FileTransport_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryDownloadStatus_(FileTransport_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientWriter< ::FileService::UploadRequest>* FileTransport::Stub::UploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::FileService::UploadRequest>::Create(channel_.get(), rpcmethod_UploadFile_, context, response);
}

void FileTransport::Stub::async::UploadFile(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::ClientWriteReactor< ::FileService::UploadRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::FileService::UploadRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::FileService::UploadRequest>* FileTransport::Stub::AsyncUploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::FileService::UploadRequest>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::FileService::UploadRequest>* FileTransport::Stub::PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::FileService::UploadResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::FileService::UploadRequest>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, false, nullptr);
}

::grpc::ClientReader< ::FileService::DownloadResponse>* FileTransport::Stub::DownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::FileService::DownloadResponse>::Create(channel_.get(), rpcmethod_DownloadFile_, context, request);
}

void FileTransport::Stub::async::DownloadFile(::grpc::ClientContext* context, const ::FileService::DownloadRequest* request, ::grpc::ClientReadReactor< ::FileService::DownloadResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::FileService::DownloadResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_DownloadFile_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::FileService::DownloadResponse>* FileTransport::Stub::AsyncDownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileService::DownloadResponse>::Create(channel_.get(), cq, rpcmethod_DownloadFile_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::FileService::DownloadResponse>* FileTransport::Stub::PrepareAsyncDownloadFileRaw(::grpc::ClientContext* context, const ::FileService::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileService::DownloadResponse>::Create(channel_.get(), cq, rpcmethod_DownloadFile_, context, request, false, nullptr);
}

::grpc::Status FileTransport::Stub::QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::FileService::UploadStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::FileService::QueryUploadRequest, ::FileService::UploadStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryUploadStatus_, context, request, response);
}

void FileTransport::Stub::async::QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::FileService::QueryUploadRequest, ::FileService::UploadStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryUploadStatus_, context, request, response, std::move(f));
}

void FileTransport::Stub::async::QueryUploadStatus(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryUploadStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::FileService::UploadStatus>* FileTransport::Stub::PrepareAsyncQueryUploadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::FileService::UploadStatus, ::FileService::QueryUploadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryUploadStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::FileService::UploadStatus>* FileTransport::Stub::AsyncQueryUploadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryUploadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryUploadStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileTransport::Stub::QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::FileService::DownloadStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::FileService::QueryDownloadRequest, ::FileService::DownloadStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryDownloadStatus_, context, request, response);
}

void FileTransport::Stub::async::QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::FileService::QueryDownloadRequest, ::FileService::DownloadStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryDownloadStatus_, context, request, response, std::move(f));
}

void FileTransport::Stub::async::QueryDownloadStatus(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryDownloadStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::FileService::DownloadStatus>* FileTransport::Stub::PrepareAsyncQueryDownloadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::FileService::DownloadStatus, ::FileService::QueryDownloadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryDownloadStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::FileService::DownloadStatus>* FileTransport::Stub::AsyncQueryDownloadStatusRaw(::grpc::ClientContext* context, const ::FileService::QueryDownloadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryDownloadStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

FileTransport::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransport_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< FileTransport::Service, ::FileService::UploadRequest, ::FileService::UploadResponse>(
          [](FileTransport::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::FileService::UploadRequest>* reader,
             ::FileService::UploadResponse* resp) {
               return service->UploadFile(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransport_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FileTransport::Service, ::FileService::DownloadRequest, ::FileService::DownloadResponse>(
          [](FileTransport::Service* service,
             ::grpc::ServerContext* ctx,
             const ::FileService::DownloadRequest* req,
             ::grpc::ServerWriter<::FileService::DownloadResponse>* writer) {
               return service->DownloadFile(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransport_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileTransport::Service, ::FileService::QueryUploadRequest, ::FileService::UploadStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileTransport::Service* service,
             ::grpc::ServerContext* ctx,
             const ::FileService::QueryUploadRequest* req,
             ::FileService::UploadStatus* resp) {
               return service->QueryUploadStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransport_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileTransport::Service, ::FileService::QueryDownloadRequest, ::FileService::DownloadStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileTransport::Service* service,
             ::grpc::ServerContext* ctx,
             const ::FileService::QueryDownloadRequest* req,
             ::FileService::DownloadStatus* resp) {
               return service->QueryDownloadStatus(ctx, req, resp);
             }, this)));
}

FileTransport::Service::~Service() {
}

::grpc::Status FileTransport::Service::UploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::FileService::UploadRequest>* reader, ::FileService::UploadResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileTransport::Service::DownloadFile(::grpc::ServerContext* context, const ::FileService::DownloadRequest* request, ::grpc::ServerWriter< ::FileService::DownloadResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileTransport::Service::QueryUploadStatus(::grpc::ServerContext* context, const ::FileService::QueryUploadRequest* request, ::FileService::UploadStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileTransport::Service::QueryDownloadStatus(::grpc::ServerContext* context, const ::FileService::QueryDownloadRequest* request, ::FileService::DownloadStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace FileService
#include <grpcpp/ports_undef.inc>

